iqlusioninc/abscissa

- Cargo.toml
- README.md
- abscissa_derive/Cargo.toml
- abscissa_derive/README.md
- abscissa_derive/src/lib.rs
- src/lib.rs
Fixes lingering references to `iqlusion/crates`
> Fixups from after splitting Abscissa into its own project

- README.md
They eat up an awful lot of horizontal space and make the table a bit more cramped, particularly on crates.io mobile
> README.md: Omit winapi-* platform gems from table

- Cargo.toml
- src/util.rs
We already pull in Chrono as a dependency via the `simplelog` crate (when logging is enabled). Might as well export it through `util` in case apps want to use it for their own purposes.
> util.rs: Export the "chrono" crate under "util::time"

- .gitignore
- Cargo.lock
This will make it easier to spot changes to Abscissa's dependencies when crates are added, removed, or updated.
> Cargo.lock: Check into repository

- src/application/mod.rs
This allows `main.rs` for an Abscissa application to look like:
```
extern crate myapp;
use myapp::{Application, MyApp};
fn main() {
MyApp::boot();
}
```
> Application: add boot() method to trait

- .travis.yml
- Cargo.lock
- Cargo.toml
- README.md
- appveyor.yml
- tests/app/README.md
- tests/app/metadata.rs
- tests/generated_app.rs
Performs a set of integration tests against a generated Abscissa application using a Rust-based test harness in `tests/generated_app.rs`
Presently runs the following against generated apps:
- `cargo fmt -- --check`
- `cargo test --release`
- `cargo run -- --version`
- `cargo clippy`
Additionally, a set of test files in `tests/app` are copied into the generated app's `tests/` directory, allowing tests to easily be run against the newly generated application without having to include them in the application template.
> tests/generated_app: Rust-powered generated app tester

- .travis.yml
- README.md
- appveyor.yml
- src/lib.rs
Notably `Box<Fn*>` was stabilized and is quite useful.
This should, hopefully, represent a minimum version we'll be able to stick with for awhile.
> Bump minimum Rust version to 1.35.0

- src/runnable.rs
Rust 1.35 added support for `Box<dyn Fn>` and `Box<dyn FnMut>`.
We're officially now 1.35+, so add `Runnable`/`RunnableMut` impls for these respectively.
It's convenient to be able to create anonynous `Runnable`s out of boxed closures.
> Impl Runnable/RunnableMut for Box<dyn Fn/FnMut>

- abscissa_derive/src/command.rs
- abscissa_derive/src/config.rs
- abscissa_derive/src/lib.rs
- abscissa_derive/src/runnable.rs
Adds tests for all proc macros using synstructure's `test_derive!` macro
> abscissa_derive: Test all proc macros

- abscissa_generator/src/template/collection.rs
- abscissa_generator/template/src/application.rs.hbs
- abscissa_generator/template/src/commands/start.rs.hbs
- abscissa_generator/template/src/lib.rs.hbs
- abscissa_generator/template/src/prelude.rs.hbs
- src/config.rs
- src/config/merge.rs
- src/config/reader.rs
- src/lib.rs
Adds a set of accessors to the application template:
- `app_config()`: obtain a `config::Reader` for reading app config
- `app_reader()`: obtain a concurrent read-only lock on app state
- `app_writer()`: obtain an exclusive mutable lock on app state
Additionally it adds a `prelude` module to each application which is useful for easily importing common application-specific types/macros.
> Add app_config()/app_reader()/app_writer() and prelude to template

- Cargo.lock
- Cargo.toml
- abscissa_generator/src/properties/framework.rs
- src/config.rs
This upgrades to using secrecy 0.2, and enables the crate's "serde" feature, allowing deserialization of secrets contained in configuration files.
Additionally, it removes the `Clone + Serialize` bounds on configs, as these are not amenable to secrets kept in config files.
> Upgrade to secrecy 0.2; enable serde feature

- README.md
- abscissa_generator/src/properties.rs
- abscissa_generator/src/properties/name.rs
- abscissa_generator/template/src/commands.rs.hbs
- abscissa_generator/template/src/error.rs.hbs
- src/bin/abscissa/commands/new.rs
...instead of a custom per-app error type. This is shorter and more convenient.
> abscissa_generator: Use Error/ErrorKind names

- src/command/entrypoint.rs
Determines path to configuration using the command-line argument
> command/entrypoint: Use config arg

- Cargo.lock
- abscissa_derive/Cargo.toml
- abscissa_derive/src/command.rs
- abscissa_derive/src/runnable.rs
- abscissa_generator/template/src/commands.rs.hbs
- abscissa_generator/template/src/commands/start.rs.hbs
- abscissa_generator/template/src/commands/version.rs.hbs
- src/bin/abscissa/commands/version.rs
- src/command.rs
- src/command/entrypoint.rs
- src/command/help.rs
- src/command/usage.rs
- src/lib.rs
- src/terminal.rs
- tests/generate_app.rs
Adds a `termcolor`-powered presenter for displaying usage information for commands.
Supports nested subcommands of unbounded depth.
Additionally adds `abscissa::command::Help` which provides a generic help command usable with any parent `Command`, and uses it in the default template.
> Command usage improvements

- src/command/usage.rs
In the event arguments fail to parse, and no arguments have been given, this prints the command usage without error rather than an error and exiting with an error status.
It's a bit friendlier to new users.
> command: Show full usage on error with no args

- Cargo.lock
- Cargo.toml
- abscissa_generator/template/Cargo.toml.hbs
- src/error/framework.rs
- src/lib.rs
- src/testing.rs
- tests/generate_app.rs
Adds an `abscissa::testing` module with `CargoRunner` and `CmdRunner` which is gated under the `testing` feature.
Enables the `testing` feature in the application boilerplate under `dev-dependencies`.
Rewrites the existing app generator tests using this new functionality (which is partially extracted from the original app generator tests), exercising the test subsystem in an act of test inception.
> testing: Add initial testing subsystem

- abscissa_generator/template/src/commands/start.rs.hbs
- abscissa_generator/template/tests/acceptance.rs.hbs
- src/bin/abscissa/commands.rs
- src/command/entrypoint.rs
- tests/app/exit_status.rs
`Entrypoint` was not properly thunking `subcommand_usage` previously.
Also adds some more interesting acceptance tests to the generated template.
> Fix usage parsing for entrypoint command

- Cargo.toml
- abscissa_generator/template/src/application.rs.hbs
- src/application.rs
- src/bin/abscissa/application.rs
- src/lib.rs
- src/logging.rs
- src/logging/component.rs
- src/logging/config.rs
- src/logging/logger.rs
The new logging subsystem lacked support for configuring the loglevel.
This commit adds it back.
> logging: Fix LevelFilter support

- Cargo.lock
- Cargo.toml
- appveyor.yml
- src/bin/abscissa/commands/new.rs
- src/command/usage.rs
- tests/app/metadata.rs
- tests/generate_app.rs
Overwrites existing files.
Uses it as part of the tests, as opposed to a tempdir, which both eliminates the dependency and significantly speeds the tests up in cases where files haven't been modified.
> abscissa new: add --force option

- abscissa_generator/src/lib.rs
- src/bin/abscissa/commands/new.rs
- src/bin/abscissa/main.rs
This is convenient and common in these sorts of generators, e.g. both `cargo new` and `rails new` do it.
> generator: Run 'git init' automatically

- abscissa_generator/template/tests/acceptance.rs.hbs
- src/lib.rs
- src/testing.rs
- tests/app/exit_status.rs
- tests/generate_app.rs
Changes the `::run` and `::status` methods to panic, removing the need for users writing tests to call `unwrap()` on them.
It doesn't make sense for end-users to handle these errors, so this improves the ergonomics by making the API simpler.
> testing: Simplify error handling

- README.md
- abscissa_generator/template/Cargo.toml.hbs
Unfortunately this whole table is presently managed by hand. It would be nice to automate in the future.
This change also disables default features for the `abscissa` dev dependencies in the template, as otherwise it pulls in `abscissa_generator` and all of its associated dependencies.
> README.md: Update dependencies table

- abscissa_generator/template/src/commands.rs.hbs
- abscissa_generator/template/src/commands/start.rs.hbs
- src/application.rs
- src/command/entrypoint.rs
- src/config.rs
- src/config/configurable.rs
- src/config/overrides.rs
- Have `command::EntryPoint` delegate its `Configurable` impl to the command it wraps.
- Simplify configuration loading logic in `Application`.
- Rename `config::MergeOptions` to `config::Override` and provide an example of how to use it in the boilerplate.
> Configuration loading improvements (fixes #79)

- abscissa_generator/template/src/commands.rs.hbs
This adds boilerplate which includes the config filename, checks if it exists, and if not, ignores it.
Including this check in the boilerplate, and the explanatory comments around it, should hopefully be sufficient to address questions in #80.
> generator: Add config filename boilerplate to template (closes #80)

- .travis.yml
Travis's macOS builders are slow.
Ideally we'd hard fail on this, but doing so slows down build times.
> .travis.yml: Allow macOS build failures

- abscissa_generator/template/src/commands/start.rs.hbs
- abscissa_generator/template/src/config.rs.hbs
This might be something the framework should require and leverage, so apps always have a default configuration to start with which is replaced with values from the config file once loaded.
For now though, the framework does not require the config types impl `Default`, and it's merely a recommended best practice (it is potentially very helpful for testing).
> generator: Add Default impl to generated config

- abscissa_generator/template/src/config.rs.hbs
This was previously added to the toplevel struct, but not this inner struct.
> generator: Add 'serde(deny_unknown_fields)'

- README.md
No-longer used (due to `std` support for byte order conversions)
> README.md: Remove 'byteorder' from deps list

- abscissa_generator/template/src/application.rs.hbs
- abscissa_generator/template/src/commands/start.rs.hbs
- abscissa_generator/template/src/config.rs.hbs
- abscissa_generator/template/tests/acceptance.rs.hbs
- src/application.rs
- src/bin/abscissa/application.rs
- src/bin/abscissa/config.rs
- src/command/entrypoint.rs
- src/component.rs
- src/component/registry.rs
- src/config.rs
- src/config/reader.rs
- src/logging/component.rs
- src/terminal/component.rs
- src/testing.rs
- src/testing/config.rs
- src/testing/runner.rs
- tests/app/exit_status.rs
- tests/app/metadata.rs
Changes the bounds on `abscissa::Config` so `Default` is now required.
Uses the default configuration value when none has been provided.
> config: Mandate Default bound + testing support

- abscissa_generator/template/tests/acceptance.rs.hbs
- src/testing.rs
- src/testing/process/streams.rs
- src/testing/regex.rs
Eliminates "stringly" typed Regex API by using a new type with `From` impls appropriate to the testing use case.
> testing: Add Regex newtype

- Cargo.lock
- abscissa_generator/Cargo.toml
- abscissa_generator/src/template/collection.rs
- abscissa_generator/src/template/iter.rs
handlebars 2.0.0 -> 2.0.1 upgraded `hashbrown` versions from 0.4 to 0.5 and in doing so broke the Abscissa v0.1 release, which now has an older incompatible v0.4. I've opened an upstream issue about this here:
https://github.com/sunng87/handlebars-rust/issues/279
To avoid this in the future, this change removes the external dependency. The implementation is a bit hacky, but gets the job done.
> generator: Remove hashbrown dependency

- core/src/command/usage.rs
Previously this would panic in the event the user provided a valid subcommand which is an enum containing only other subcommands.
This fixes that error to display usage for that parent command.
> usage: Fix panic when printing usage on error

- core/src/component/registry.rs
> Bugfix: allow Registry::iter() without mutable reference

- core/src/component/id.rs
- core/src/component/registry.rs
- core/src/logging/component.rs
- core/src/terminal/component.rs
- core/tests/component.rs
- core/tests/example_app/mod.rs
Adds a set of tests to `abscissa_core` for basic component registry behaviors like registering components and getting registered components.
> Initial component tests

- core/src/component.rs
- core/src/component/registry.rs
- core/tests/component.rs
Support for getting concrete types from the component registry.
This presently doesn't ensure types are unique, or index them by their `TypeId`, but these things would probably be good ideas.
> component: Add `get_downcast_ref`/`get_downcast_mut` to Registry

- core/src/application.rs
- core/src/application/state.rs
- core/src/component.rs
- core/src/component/registry.rs
Adds a secondary TypeId index which can be used to look components up by type, rather than iterating over all registered components and trying to downcast them.
This will also ensure that only one instance of each component type is allowed to be registered.
Adding this requires a `'static` bound on the component registry's application type.
> component: Index Registry by TypeId

- core/src/command.rs
- core/src/component.rs
- core/src/config.rs
- core/src/lib.rs
- core/src/logging/component.rs
- core/src/runnable.rs
- core/src/terminal/component.rs
- core/tests/component.rs
- derive/src/component.rs
- derive/src/lib.rs
Adds custom derive support for `Component` which computes the `component::Id` automatically and sources the `Version` from the current crate version.
> derive: Custom derive support for `Component`

- Cargo.lock
- README.md
- cli/Cargo.toml
- core/Cargo.toml
- core/src/application.rs
- core/src/component.rs
- core/src/component/registry.rs
- core/src/logging.rs
- core/src/logging/component.rs
- core/src/terminal.rs
- core/src/terminal/component.rs
- core/tests/component.rs
- derive/Cargo.toml
- derive/src/component.rs
Adds a custom attribute used by `derive(Component)` to derive the `Component::register_dependency` method, handling type conversions along the way.
Uses proc macros to downcast components to the requested type. For now it seems to be working out.
Tests dependency injection by reversing component order, letting the registry sort them by their dependencies and then invoke the appropriate callbacks. Tests the callbacks were actually fired.
Adds the `darling` crate as a proc macro attribute parser because it is
amazing and we should totally use it anywhere we deal with attributes.
> component: Add #[dependencies(...)] attribute

- core/src/component/registry.rs
- core/tests/component.rs
The previous implementation would encounter errors after adding components to the `Arena`, and then try to clean up changes, which accidentally deleted a key from the index in the process.
This error was captured in a test, then corrected by first ensuring that registration would succeed before performing any state mutations.
Thanks to @dirvine for pointing out something was fishy.
> component: Ensure registration will succeed before mutating

- Cargo.lock
- README.md
- cli/Cargo.toml
- cli/src/commands/new.rs
- cli/src/properties/name.rs
- cli/template/Cargo.toml.hbs
- cli/template/src/commands.rs.hbs
- cli/template/src/commands/start.rs.hbs
- cli/template/src/commands/version.rs.hbs
- cli/template/src/lib.rs.hbs
- core/src/lib.rs
- derive/Cargo.toml
- derive/src/command.rs
The `ident_case` crate has equivalent functionality and is used by the `darling` crate, so be parsimonious and only use one.
This PR also handles dashes in the app name, and therefore closes #100.
> Switch from `heck` to `ident_case` (closes #100)

- core/src/command/usage.rs
This avoids selecting white as a specific color, and instead just makes the section headers and crate name bold.
This fixes legibility on light terminal backgrounds. Example:
> usage: Use bold rather than explicit color (fixes #105)

- cli/template/src/error.rs.hbs
The `Error` type defined by the template is a thin newtype around `abscissa::Error`. Unfortunately the template defines a completely opaque newtype!
This adds a `Deref` impl to it which makes it easy to call any methods on `abscissa::Error`.
> template: Add Deref impl on Error newtype

- AUTHORS.md
- core/src/signal.rs
- core/src/thread/manager.rs
I was also thinking of adding a helper for creating the signal handler, similiar to the existing prelude-included helpers for application state
```diff
diff --git a/cli/template/src/application.rs.hbs b/cli/template/src/application.rs.hbs
index 8c55f9a..17cfbb5 100644
--- a/cli/template/src/application.rs.hbs
+++ b/cli/template/src/application.rs.hbs
@@ -2,7 +2,7 @@
use crate::{commands::{{~command_type~}}, config::{{~config_type~}}};
use abscissa_core::{
-    application, config, logging, Application, EntryPoint, FrameworkError, StandardPaths,
+    application, config, logging, signal, Application, EntryPoint, FrameworkError, StandardPaths,
};
use lazy_static::lazy_static;
@@ -30,6 +30,24 @@ pub fn app_config() -> config::Reader<{{~application_type~}}> {
config::Reader::new(&APPLICATION) …
```
> Fix issues with the signal handler thread

- Cargo.lock
- derive/Cargo.toml
- derive/src/command.rs
...and bumps synstructure and darling to releases which use these too.
> derive: Update to 1.0 versions of proc-macro2/quote/syn

- Cargo.lock
- cli/Cargo.toml
- cli/template/Cargo.toml.hbs
- core/Cargo.toml
...and with the release of `failure` v0.1.6, this means we no-longer depend on any pre-1.0 core proc macro crates.
> Update dependencies: gumdrop 0.7, secrecy 0.4

- cli/template/src/lib.rs.hbs
- cli/template/src/prelude.rs.hbs
- cli/template/tests/acceptance.rs.hbs
- Adds `missing_docs` to the list of warnings in template-generated files
- Re-export all status macros via the prelude
> template: Warn for missing docs; re-export status macros via prelude

- Cargo.lock
- README.md
- core/Cargo.toml
- core/src/terminal/component.rs
The `color-backtrace` crate provides colorized, richly formatted backtraces when crashes occur:
https://github.com/athre0z/color-backtrace
When built with debug symbols, it's also capable of displaying the relevant source code for each stack frame in the backtrace.
With `default-features = false`, it's nicely parsimonious with our existing dependencies, and only adds a single additional transitive dependency, `atty` (which we previously used, and should potentially consider using again).
> terminal: Add `color-backtrace` crate

- Cargo.lock
- cli/template/Cargo.toml.hbs
- core/Cargo.toml
The `gimli` crate is an optional alternative backend for the `backtrace` crate based on a pure-Rust DWARF parser as opposed to `libbacktrace`, which is written in C. The long-term plan is to make `gimli` the default backend for the `backtrace` crate (which will eventually be include in `std` and is presently available on `nightly`).
For more information, see:
https://github.com/rust-lang/backtrace-rs/issues/189
This adds considerably to Cargo.toml as `gimli` has quite a few dependencies, and because of that, it's left off-by-default, but with a commented-out option to activate it in the template's Cargo.toml.
> Add `gimli-backtrace` Cargo feature

- Cargo.lock
- README.md
- cli/Cargo.toml
- cli/src/commands/new.rs
- cli/src/error.rs
- cli/src/lib.rs
- cli/src/prelude.rs
- cli/src/template/collection.rs
- cli/template/Cargo.toml.hbs
- cli/template/src/prelude.rs.hbs
- core/Cargo.toml
- core/src/application.rs
- core/src/application/exit.rs
- core/src/component.rs
- core/src/component/registry.rs
- core/src/config.rs
- core/src/config/configurable.rs
- core/src/error.rs
- core/src/error/context.rs
- core/src/error/framework.rs
- core/src/error/macros.rs
- core/src/error/message.rs
- core/src/lib.rs
- core/src/path.rs
- core/src/signal.rs
- core/src/terminal/status.rs
- core/src/testing/process.rs
- core/src/thread.rs
- core/src/thread/manager.rs
Since the time `failure` was written, `std::error::Error` has gained many of the features it was originally useful for, most notably `Error::source` for type-erased error chains/cascades (with downcast
support to recover the concrete type, if desired), and on `nightly`, backtrace support.
This commit attempts to remove `failure` in a way that largely preserves the existing error handling, replacing `failure::Context` with an internal `abscissa_core::error::Context` type which provides similar functionality, and more or less replaces the previous `abscissa_core::error::Error` type.
Additionally, it defines a `BoxError` alias for type-erased errors based on ideas from this rust-internals thread:
https://internals.rust-lang.org/t/proposal-add-std-boxerror/10953/1
It's bounded as `Send + Sync …
> Remove `failure`

- Cargo.lock
- cli/Cargo.toml
- cli/src/application.rs
- cli/template/Cargo.toml.hbs
- cli/template/src/application.rs.hbs
- cli/template/tests/acceptance.rs.hbs
- cli/tests/app/README.md
- cli/tests/app/exit_status.rs
- cli/tests/generate_app.rs
- core/src/application.rs
- core/src/application/cell.rs
- core/src/application/lock.rs
- core/src/application/lock/reader.rs
- core/src/application/lock/writer.rs
- core/src/config/reader.rs
- core/src/lib.rs
This eliminates all previous usages of `lazy_static`, including in the new application template, with an `AppCell` type which is based on `OnceCell`.
Unlike `lazy_static`, `OnceCell` does not require macros, and because of that can be hidden within the framework as an implementation detail.
It's also on track for potential inclusion in the standard library, which would allow us to eventually eliminate it as a dependency:
https://github.com/rust-lang/rfcs/pull/2788
Overall, the previous usage patterns for `lazy_static` were hacking around the lack of a `OnceCell`-like API, so this is a net win.
> Completely replace `lazy_static` with `once_cell`

- cli/src/prelude.rs
- cli/template/src/prelude.rs.hbs
- core/src/lib.rs
- core/src/prelude.rs
Moving parts of the prelude into the framework itself eliminates the need to update boilerplate whenever the prelude changes.
> Split core prelude from template

- cli/src/template/collection.rs
There's a Handlebars template for `.gitignore`, but it wasn't included in this (manually maintained) list. Per the TODO it'd be nice if `build.rs` built the list automatically.
> template: Wire up .gitignore

- cli/src/commands.rs
- cli/src/commands/gen.rs
- cli/src/commands/gen/cmd.rs
- cli/src/commands/new.rs
- cli/src/config.rs
- cli/src/error.rs
- cli/src/template.rs
- cli/src/template/collection.rs
- cli/src/template/registry.rs
- cli/template/src/commands/subcommand.rs.hbs
- cli/tests/generate_app.rs
Insipired by `rails generate`, this adds a template-based boilerplate generator for adding subcommands to an existing application:
$ abscissa gen cmd foo-bar
This generates a new subcommand from a `subcommand.rs.hbs` template file which includes some examples of how to use the `gumdrop` proc macro DSL for defining command line argument parsing.
> cli: add `gen cmd` subcommand

- .github/workflows/rust.yml
- .github/workflows/security_audit.yml
- cli/src/commands/new.rs
- core/src/lib.rs
- core/src/terminal/status.rs
- core/src/trace/component.rs
It seems it wasn't properly testing a build with `--no-default-features` before, and this wasn't detected until Rust 1.40 made this a hard error.
> Fix GitHub Actions Build

- core/src/command/usage.rs
In some cases (namely `#[option(command)]` nested inside another struct) it isn't possible to retrieve usage information (i.e. `Options::command_usage` returns `None`).
This may be indicative of a bug in `gumdrop`, but regardless, when this occurs this handles the situation gracefully (usage info unavailable for that subcommand) rather than panicking.
> Workaround for #[option(command)] usage parsing

- README.md
- cli/template/Cargo.toml.hbs
- cli/template/src/error.rs.hbs
Provides handy custom derive support for `Error`:
https://github.com/dtolnay/thiserror
It's only provided in the default boilerplate and can be switched out easily.
This should hopefully otherwise close any open questions about error-handling.
> Add `thiserror` to default application boilerplate (closes #144)

- core/src/command/usage.rs
The usage subsystem always assumed the toplevel command is an `enum`.
This fixes usage when the toplevel command is a `struct`.
> usage: fix handling of toplevel `Options` structs

- .github/workflows/rust.yml
- AUTHORS.md
- Cargo.lock
- README.md
- core/Cargo.toml
This branch updates the `tracing-subscriber` dependency to version
0.2.0. This is a major release which includes a couple of important bug
fixes; in particular, we've fixed a memory leak caused by spans failing
to close their parents, and made significant improvements to performance
under high concurrency.
Since this is also a potentially breaking change, I'm trying to help
some of our major dependents update by opening PRs against projects that
use `tracing-subscriber`. However, it looks like Abscissa didn't
actually use any of the APIs we broke in this release :)
Additionally, while I'm here, I took the liberty of updating the
dependency list in the README to reflect changes in transitive
dependencies pulled in by `tracing-subscriber` and `tracing`. Several
dependencies were removed — …
> update `tracing-subscriber` to 0.2.0

- Cargo.lock
Switches to the new lockfile format, preserving the existing resolution
> Cargo.lock: update format to ResolveVersion::V2

- Cargo.lock
- Cargo.toml
- README.md
- derive/README.md
- tokio/Cargo.toml
- tokio/README.md
- tokio/src/lib.rs
Adds an `abscissa_tokio` crate containing a `TokioComponent` which manages the lifecycle for spawning a `tokio::runtime::Runtime`.
Inspired by the approach used in Zebrad:
https://github.com/ZcashFoundation/zebra/blob/4fcb550/zebrad/src/components/tokio.rs
cc @hdevalence @dconnolly
> tokio: Initial `abscissa_tokio` crate

- Cargo.lock
- core/src/testing.rs
- tokio/Cargo.toml
- tokio/src/lib.rs
Replaces the previous non-parameterized `start()` function with a `run()` function that accepts a `Future`.
This eliminates `futures-util` as a dependency, and provides an experience much closer to `tokio::main`.
> tokio: Change main API to `abscissa_tokio::run`

- cli/src/application.rs
- cli/src/bin/abscissa/main.rs
- cli/template/src/application.rs.hbs
- cli/template/src/bin/app/main.rs.hbs
- cli/template/src/commands/start.rs.hbs
- cli/template/src/prelude.rs.hbs
- core/src/application/cell.rs
- core/src/lib.rs
- core/src/terminal/status.rs
- tokio/src/lib.rs
- Shortens `APPLICATION` constant to `APP` in the template
- Re-exports `APP` via the app-local prelude
- Adds a `config()` method to `AppCell`
- Removes the `app_reqder()`, `app_writer()`, `app_config()` helpers; Use `APP.read()`, `APP.write()`, `APP.config()` instead
> cli: rename `APPLICATION` -> `APP`; export from prelude; redo helpers

- core/src/command.rs
The doc comment in question refers to a method named `call`, which does not exist anywhere within the code for Abscissa. The comment is most likely trying to refer to the `run` method, which is required by the `Runnable` trait.
I assume this was overlooked when the `Callable` trait was renamed to `Runnable`.
> Fix wrong method name in doc comment

- cli/template/src/commands/subcommand.rs.hbs
Hi there!
I'm a newbie and this one had my scratching my head for a second.
`Options` is the imported trait.
> cli/template: fix typo in example comment

- .github/workflows/rust.yml
https://rust-lang.github.io/rust-clippy/master/index.html#unnecessary_sort_by would've required a `.clone()` which want to avoid on a lifetime return type.
> Fix CI, allow clippy::unnecessary_sort_by

- Cargo.lock
- README.md
- cli/src/commands/gen/cmd.rs
- cli/src/commands/new.rs
- cli/tests/generate_app.rs
- core/Cargo.toml
- core/src/config.rs
- core/src/lib.rs
- core/src/testing/config.rs
The `fs_err` crate is a drop-in replacement for `std:::fs` with zero transitive dependencies which provides error messages that include the filename in addition to the failing operation:
https://github.com/andrewhickman/fs-err
This commit re-exports it as `abscissa_core::fs` and uses it to implement all framework-level filesystem operations.
```rust
let file = File::open("does not exist.txt")?;
```
```
The system cannot find the file specified. (os error 2)
```
```
failed to open file `does not exist.txt`
caused by: The system cannot find the file specified. (os error 2)
```
cc @yaahc
> core: add `fs_err` dependency

- Cargo.lock
Adds the following deps:
`cc` v1.0.62
`cfg-if` v1.0.0
`generator` v0.6.23
`loom` v0.3.6
`rustc_version` v0.2.3
`scoped-tls` v1.0.0
`semver` v0.9.0
Updates:
`addr2line` v0.13.0 -> v0.14.0
`aho-corasick` v0.7.13 -> v0.7.15
`backtrace` v0.3.51 -> v0.3.54
`gimli` v0.22.0 -> v0.23.0
`handlebars` v3.5.0 -> v3.5.1
`hermit-abi` v0.1.16 -> v0.1.17
`libc` v0.2.77 -> v0.2.80
`memchr` v2.3.3 -> v2.3.4
`miniz_oxide` v0.4.2 -> v0.4.3
`num-integer` v0.1.43 -> v0.1.44
`num-traits` v0.2.12 -> v0.2.14
`object` v0.20.0 -> v0.22.0
`pin-project-lite` v0.1.9 -> v0.1.11
`proc-macro2` v1.0.23 -> v1.0.24
`regex` v1.3.9 -> v1.4.2
`regex-syntax` v0.6.18 -> v0.6.21
`rustc-demangle` v0.1.16 -> v0.1.18
`serde` v1.0.116 -> v1.0.117
`serde_derive` v1.0.116 -> v1.0.117
`serde_json` v1.0.58 -> v1.0.59
`sharded-slab` …
> Cargo.lock: Update dependencies

- core/src/terminal/status.rs
fixes https://github.com/RustSec/cargo-audit/issues/293
> don't end status messages with trailing spaces if msg is empty

- core/Cargo.toml
Gimli has been enabled by-default in the `backtrace` crate for awhile, so the `gimli-backtrace` feature no longer serves any purpose.
> core: remove `gimli-backtrace` feature

- Cargo.lock
- core/Cargo.toml
- core/src/terminal/component.rs
This begins a general migration to `eyre` for error handling:
https://github.com/yaahc/color-eyre
> core: replace `color-backtrace` with `color-eyre`

- .github/workflows/cli.yml
- .github/workflows/core.yml
- .github/workflows/derive.yml
- .github/workflows/tokio.yml
- .github/workflows/workspace.yml
- Cargo.toml
- README.md
- tokio/src/lib.rs
This is needed to make progress on #540, and also lets us switch to the V2 Cargo resolver.
> Bump MSRV to 1.51+

- Cargo.lock
- cli/Cargo.toml
- cli/src/commands.rs
- cli/src/commands/gen.rs
- cli/src/commands/gen/cmd.rs
- cli/src/commands/new.rs
- cli/template/Cargo.toml.hbs
- cli/template/src/commands.rs.hbs
- cli/template/src/commands/start.rs.hbs
- cli/template/src/commands/subcommand.rs.hbs
- core/Cargo.toml
- core/src/application.rs
- core/src/command.rs
- core/src/lib.rs
- core/tests/example_app/mod.rs
The final release of `clap` v3 is out.
This commit updates to it, and attempts to do things a bit more idiomatically in regard to the upstream changes.
Namely, the re-exports have changed so only the `clap` crate itself is re-exported, and the `clap::Parser` macro is used directly rather than re-exported under the old `Clap` name.
> Update to `clap` v3.0 release

- README.md
Here's the context of this PR, a conversation on [Twitter](https://twitter.com/sunshowers6/status/1484650273276456960?t=cQIFI19SUD-fSc-c41lwCw&s=19) that made me realize we still projected gumdrop instead of clap in the `Readme.md` file. 
Please review this PR and merge / let me know ways I can improve it
> removed gumdrop from readme, edited to include clap

- core/src/application.rs
- core/src/command.rs
Clap has a separate `Subcommand` trait which is used instead of `Parser` on enums which represent subcommands.
For that reason `Command` can't directly bound on `Parser` and still be usable for subcommand enums.
Instead this commit changes `Command` to bound on the more general `clap::FromArgMatches` trait and moves the `clap::Parser` bound to the relevant methods for parsing toplevel arguments such as `parse_args` and `parse_env_args`.
> Change `clap` bounds for `Command` from `Parser` to `FromArgMatches`

- README.md
- cli/Cargo.toml
- cli/src/lib.rs
- core/Cargo.toml
- core/src/lib.rs
- derive/Cargo.toml
- derive/README.md
- derive/src/lib.rs
- tokio/Cargo.toml
- tokio/README.md
- tokio/src/lib.rs
- Logos were 404ing; source them from GitHub
- Bump all MSRV docs and configs to 1.60 to reflect true MSRV
> Fix logo URLs and MSRV documentation

- README.md
Refactored `rustic` to use abscissa in https://github.com/rustic-rs/rustic/pull/617, this PR adds `rustic` to the list of projects.
> Add `rustic` to Readme as a project using abscissa

- README.md
Follow up of https://github.com/iqlusioninc/abscissa/pull/848#issuecomment-1599633363
> Remove OpenLibra, update Tendermind KMS repository link, and move cargo-rpm to `Archived` subheading

- core/src/trace/config.rs
Closes https://github.com/iqlusioninc/abscissa/issues/862
> fix: uses default info if RUST_LOG is not set

- Cargo.lock
- core/src/lib.rs
Updates the following dependencies:
$ cargo update
Updating crates.io index
Locking 55 packages to latest compatible versions
Updating actix-rt v2.9.0 -> v2.10.0
Updating anstream v0.6.13 -> v0.6.15
Updating anstyle v1.0.6 -> v1.0.8
Updating anstyle-parse v0.2.3 -> v0.2.5
Updating anstyle-query v1.0.2 -> v1.1.1
Updating anstyle-wincon v3.0.2 -> v3.0.4
Updating autocfg v1.2.0 -> v1.3.0
Updating bitflags v2.5.0 -> v2.6.0
Updating cc v1.0.96 -> v1.1.7
Updating clap v4.5.4 -> v4.5.12
Updating clap_builder v4.5.2 -> v4.5.12
Updating clap_derive v4.5.4 -> v4.5.11
Updating clap_lex v0.7.0 -> v0.7.2
Updating colorchoice v1.0.0 -> v1.0.2
Adding is_terminal_polyfill v1.70.1
Updating lazy_static v1.4.0 -> v1.5.0
Updating libc v0.2.154 -> v0.2.155
Updating log v0.4.21 -> v0.4.22
Updating memchr …
> Cargo.lock: bump dependencies

- README.md
Hi,
I stumbled across the docs referring to the `hello` subcommand, when in the current version the default is the `start` subcommand. I went ahead and fixed the `README.md`.
I was unsure whether to change `config.rs.hbs`, as well, and now I am unsure about all of it. The `start` command actually *does just say "hello"*, so maybe, instead the command should be renamed to `hello` again?
Either way, this PR makes the docs match the actual command that can be run, so it should hopefully be an improvement.
Thanks for building this! 
Cheers,
R
PS: I've read the contributing guidelines. I don't think it'd be appropriate to be listed under authors for this trivial change. Let me know if it's absolutely vital. In any case, I license my "contribution" under the terms of the Apache License, Version …
> fix docs so they refer to start subcommand instead of hello

- cli/tests/app/exit_status.rs
- cli/tests/generate_app.rs
- derive/src/command.rs
- derive/src/component.rs
- derive/src/runnable.rs
Fixes CI. Fixes useless warnings for abscissa-derive users.
> Wrangle warnings

- core/src/terminal/status.rs
in order to fix https://github.com/rustsec/rustsec/issues/1314
This is a behavioral change observable through the command-line interface, it's up to you how breaking you consider that.
> Print all status messages to stderr
