iqlusioninc/abscissa

- .circleci/config.yml
- abscissa_derive/src/options/mod.rs
- src/application/mod.rs
- src/macros/error.rs
Macros which shutdown an application while invoking its shutdown hooks prior to exiting.
> Add 'fatal!' and 'fatal_error!' macros

- .travis.yml
- Cargo.lock
- Cargo.toml
- README.md
- abscissa_derive/Cargo.toml
- abscissa_derive/README.md
- appveyor.yml
- src/error/framework.rs
- src/lib.rs
- src/shell/stream.rs
Switches the main branch to `develop` and updates various dependencies
> Updates for develop branch and outdated dependencies

- abscissa_generator/src/properties/name.rs
- src/bin/abscissa/commands/new.rs
Previously they were "CamelCase"
> abscissa_generator: Use "Title Case" titles

- abscissa_derive/src/lib.rs
- abscissa_generator/template/src/commands.rs.hbs
- abscissa_generator/template/src/commands/start.rs.hbs
- abscissa_generator/template/src/commands/version.rs.hbs
- src/application.rs
- src/bin/abscissa/commands.rs
- src/bin/abscissa/commands/new.rs
- src/bin/abscissa/commands/version.rs
- src/command.rs
- src/command/entrypoint.rs
- src/lib.rs
- src/runnable.rs
- tests/generate_app.rs
Echoes of Java, but this name better captures the intent, and the familiarity for those who've used a Runnable in the past is probably for the best.
> Rename Callable to Runnable

- Cargo.lock
- Cargo.toml
- abscissa_generator/src/template/collection.rs
- abscissa_generator/template/tests/acceptance.rs.hbs
- src/testing.rs
- tests/app/exit_status.rs
- tests/generate_app.rs
Adds support for interacting with stdin/stdout/stderr as part of acceptance tests.
> testing: Support for capturing/asserting on streams

- src/component.rs
- src/component/registry.rs
A pattern that may prove useful for `dyn Component` generally...
> component: impl PartialOrd for Box<dyn Component>

- src/component/registry.rs
Obtain references to concrete component types from `component::Registry`
> components: Add basic downcasting support

- CHANGES.md
Moves all links into the bottom of the file
> CHANGES.md: Redo formatting

- Cargo.lock
- abscissa_generator/Cargo.toml
Final version has been released (was previously using `beta.3`)
> Upgrade to handlebars v2

- AUTHORS.md
- CONTRIBUTING.md
- README.md
Notes about what contributions will be accepted and how to ensure changes are licensed correctly.
> CONTRIBUTING.md: Initial contributing guidelines

- core/src/command/usage.rs
Properly recurses through nested subcommands when displaying usage info
> usage: Fix bugs when traversing subcommands

- core/src/component/registry.rs
Here's a very quick and dirty fix to get the Registry working.
Rel: #111
> Quick fix for broken Registry component.

- README.md
The previous description was for the ordinate, not abscissa.
> README.md: Update FAQ (closes #104)

- README.md
Also tidy up a few things in the dependencies table
> README.md: Add "Projects Using Abscissa"

- core/src/command/usage.rs
This is preliminary support for handling positional ("free") arguments from gumdrop in the custom logic used for presenting usage descriptions.
- it appears no usage section is printed at all in this case, but I think it should be added for clarity
> Support positional arguments in usage descriptions

- .travis.yml
- Cargo.lock
- README.md
- core/Cargo.toml
Changelog: https://github.com/iqlusioninc/crates/pull/254
> core: Bump `secrecy` to v0.3

- .github/workflows/rust.yml
Might hopefully improve build times
> .github: Use actions/cache@v1 to cache test build artifacts

- Cargo.lock
- core/Cargo.toml
Release notes: https://github.com/iqlusioninc/crates/pull/313
> Upgrade `secrecy` crate to v0.6

- Cargo.lock
- README.md
- cli/Cargo.toml
- core/Cargo.toml
- derive/Cargo.toml
- derive/README.md
> v0.5.0-rc.0

- CHANGES.md
- cli/template/src/error.rs.hbs
Instructions on how to upgrade existing applications
> v0.5.0 release notes

- cli/src/commands/new.rs
- cli/src/error.rs
Automatically generates `Cargo.lock` when making a new app.
> cli: automatically generate Cargo.lock

- Cargo.lock
- tokio/Cargo.toml
- tokio/src/lib.rs
> abscissa_tokio v0.5.0

- .github/workflows/rust.yml
- README.md
- core/src/command/usage.rs
Technically #390 changed MSRV. This bumps it in the GitHub Actions config and documentation.
> MSRV 1.45+

- .github/workflows/rust.yml
- .github/workflows/security_audit.yml
- AUTHORS.md
- CONTRIBUTING.md
- README.md
- cli/Cargo.toml
- core/Cargo.toml
- derive/Cargo.toml
- derive/README.md
- tokio/Cargo.toml
- tokio/README.md
This seems to be the new convention for a default branch.
> Rename default git branch to `main`

- README.md
- derive/README.md
- tokio/README.md
Updates the badges to use the new GH Actions workflow names.
> README.md(s): update CI badges

- Cargo.lock
- tokio/Cargo.toml
- tokio/src/lib.rs
A feature flagged mechanism for getting access to the actix runtime info.
> A feature flagged mechanism for getting access to actix

- Cargo.lock
- core/Cargo.toml
- derive/Cargo.toml
> Cargo.lock: bump dependencies

- cli/src/commands/new.rs
...when `abscissa new` runs `git init`
> Use `main` as the default branch name

- cli/src/commands/new.rs
- core/src/trace/config.rs
> Closes #228 and adds support for RUST_LOG

- Cargo.lock
- README.md
- cli/Cargo.toml
- core/Cargo.toml
- derive/Cargo.toml
- tokio/Cargo.toml
This includes a bump to `clap` v3.0.0-beta.5
> v0.6.0-beta.1

- cli/tests/generate_app.rs
- core/tests/component.rs
There were some minor things, that popped up.
> test: fix lints

- core/README.md
- core/src/lib.rs
It's broken when publishing a crate
> core: fix README.md

- CHANGELOG.md
- Cargo.lock
- core/Cargo.toml
- Path to README.md for `abscissa_core` ([#932])
[#932]: https://github.com/iqlusioninc/abscissa/pull/932
> abscissa_core v0.8.1

- cli/README.md
- cli/src/lib.rs
Similar fix to #932: it's broken when publishing a crate
> cli: fix README.md

- tokio/src/lib.rs
The application has no way to access the runtime once `abscissa_tokio::run` is called, so it has no way to cooperatively shut down spawned tasks. The current only alternative is to hard-code a fixed timeout; this PR adds the option of using `tokio`'s built-int shutdown timer so that the timeout is only the maximum time the application will wait.
> tokio: Add a shutdown timeout to give spawned work time to stop
